services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=ats'
      - 'POSTGRES_PASSWORD=ats_admin'
      - 'POSTGRES_USER=ats_admin'
    ports:
      - '5432:5432'
