spring.datasource.url=jdbc:postgresql://localhost:5432/ats
spring.datasource.username=ats_admin
spring.datasource.password=ats_admin


spring.ai.openai.api-key=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